language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIARFZMF5W3MJMN6ULS
  secret_access_key:
    secure: XB9Rr8A8iOn1P4N+Y6E+twuiUbxS7k7T+qFJnzbrpTAj1mSXGRvbtLdu5Dl/9qm9l9rvDF7qJNrkA1zxrG+ysHHpn+0iQ29gw6DQXAymgkV6wkRllS3nv3BqxKBbXaEL0/vc9BeEhbRiGTfu7xfcRuXcIhtwuUL3ciMJOWqPoVBfPOI+yHzffpoYpegYlYiusL+YnkX8TE5jC6+ttqE6EfAPl9T0q4kee3bbfY7esUz9FI1EwrK5wiQ5T0f4UoVU5tnrMDuJr7gZ1hTT0EM7HQok1Iu1lp9yvrVj/pAdypaUM2pR94c8CbQdypP4M18nhyipw8j1mLucjsyTr4e0k5q4yPVrg3HEh+PxmD8jp3hv1YkIspUqb70GFjR2SrPYG6Wcm6iBbzBD7GclcXYiPd/xYFeKzzO5/G0E+Mte3z+ucRcUGJ/ibUi2vgwkX3J2bSIMq0xh3oaOeMQT2NECd9NZUJgduZ/xDvF6liOh1BDEIK5qqLSFhG5k1g+0xBclvgilpNKWiYe+76Zy2i91LgytzAeuJG7gBSp9chzAMzhluuxjlO+FX+ZGdTiUUo64wTjoubYgfoLfxcAIuJETkdWCH9IiO9KD5XwW6ycjHE+c6sJ13RD2xk9CzC5hAkjbNDfvbA8wPHSvo5IDJCKzbIHETdls0ZUDlSFxaKxMPpQ=
  bucket: testesi4
  edge: true
  acl: public_read
