language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: s3
  access_key_id: AKIA54T5BOOJ3GGRNE7G
  secret_access_key: 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
  bucket: testdcecole
  region: eu-west-3
  skip_cleanup: true
  local_dir: build
  acl: public_read